config/routes.rb
Rails.application.routes.draw do
  resources :estados
<<<<<<< HEAD
  resources :vendas_mensais
  match 'relatorio_vendas_mensais' => 'vendas_mensais#relatorio_vendas_mensais', via: 'get'

=======
  resources :teste_estado
  
>>>>>>> acf7a4d1b3be308fcf2d0a261f9eadfcc65568c4

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cidade.rb
class Cidade < ApplicationRecord
end

app/models/estado.rb
class Estado < ApplicationRecord

	def to_s
		self.nome
	end

	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
    
    @estado.update({atualizado_por: "Mizael"})
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:nome)
    end
end

app/controllers/teste_estado_controller.rb
class TesteEstadoController < ApplicationController

	
	def consulta

		nome_param = "%#{params[:nome].to_s}%"
  		#nome_param = '%p%'

  		#@estados = Estado.where('nome like :parametro', {parametro: nome})
  		#@estados = Estado.find(:all, :select => "name, address", :conditions => { .... } )
  		#@estados  = Estado.where("id = ? and id = ?", nome_param, 3)
  		#@estados  = Estado.all
  		#@estados = Estado.where('nome like :nome', {nome: nome_param}).order('nome DESC').limit(2)
  		@estados = Estado.where('nome like :nome', {nome: nome_param})

  		redirect_to :controller => "teste_estado", :action => "index", :resultado => @estados
    end

	def index
   		
   		@estados = ['teste','teste2']
   		@estados = params[:resultado]  		
   		
  		
		
			
    end

    
end

app/controllers/vendas_mensais_controller.rb
class VendasMensaisController < ApplicationController

	def index

		@nome = 'Helves Jhon'
		
	end

	def relatorio_vendas_mensais

	end

	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/teste_estado_helper.rb
module TesteEstadoHelper
end

app/helpers/vendas_mensais_helper.rb
module VendasMensaisHelper
end

app/views/estados/_form.html.erb
<%= form_with(model: estado, local: true) do |form| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :estado_nome %>
  </div>

  <div class="field">
    <%= form.label :atualizado_por %>
    <%= form.text_field :atualizado_por, id: :estado_atualizado_por %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>Editing Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>


<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Atualizado por</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.nome %></td>
        <td><%= estado.atualizado_por %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @estado.nome %>
</p>

<p>
  <strong>Atualizado por:</strong>
  <%= @estado.atualizado_por %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Analyticsbi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag "AdminLTE.min.css" %>
    <%= stylesheet_link_tag "bootstrap.css" %>
	<%= stylesheet_link_tag "bootstrap.min.css" %>
	<%= stylesheet_link_tag "bootstrap-theme.css" %>
	<%= stylesheet_link_tag "bootstrap-theme.min.css" %>		

	<%= javascript_include_tag "bootstrap.js"  %>
	<%= javascript_include_tag "bootstrap.min.js"  %>
	<%= javascript_include_tag "npm.js"  %>
	
	




  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/teste_estado/_estados.html.erb
<p>Estou na action1!</p> 


<% @estados.each do |estado| %>

<%= estado.to_s %>

<% end %>

app/views/teste_estado/index.html.erb
<p>Estou no controller de teste estados!</p> 


<%= form_tag('/teste_estado/consulta') do -%>
  <%= label_tag("Nome:") %>
  <%= text_field :nome %> <br/>
  <%= submit_tag("Pesquisar") %>
<% end %>




<% @estados.each do |estado| %>

<%= estado.to_s %>

<% end %>

app/views/vendas_mensais/index.html.erb
<h1>Emitir relatório de vendas mensais</h1>

<p>Formulário <%= "teste" %> </p>

<p>Nome: <%= @nome %></p>


<%= link_to "Relatório vendas mensais", controller: "vendas_mensais", action: "relatorio_vendas_mensais" %>

app/views/vendas_mensais/relatorio_vendas_mensais.html.erb
<h1>teste</h1>